version: '3.8'

services:
  web:
    build: .
    ports:
      - "7860:7860"
    volumes:
      - ./improvements:/app/improvements
      - ./.env:/app/.env:ro
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - MODEL_NAME=${MODEL_NAME}
      - MAX_TOKENS=${MAX_TOKENS}
      - TEMPERATURE=${TEMPERATURE}
      - CHUNK_SIZE=${CHUNK_SIZE}
      - CONTEXT_WINDOW=${CONTEXT_WINDOW}
      - BASE_URL=${BASE_URL}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"